before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HPJEd8D5M0x4+bMcls7WodLT091hBwWjRMwOyt+csiB/ygUFCq/3F2TTTD83fGT/ki72RlcvVj5NHwR8Hg9Gd/04aAwMTXhZKZzmRZZRAac+wrmLDs+pwpsSM2fIvut7tL5ojaVRsDRozBoKnd5jg33wpFELIvi62rLYQkmo6CE/SIRXKgCwjB2XOlRfEA6qzUijcouERxsoBHIt1IjKeqxSAlkT8ycog++38rcL03ppoZ7u+5eybguSgKC+Emr5D9XDmwq/Uej0bCcszqFadiJiGmcma9NMxdtyPTxRw9OuJJfNAMgPyZSemyu+NV7tUntzoyOi5Pzb70npVl3uImyNpbwmVvA+Tta5Mx6pyyR6+hu0yuVcDWbSiNGLPr92GOtTBNdanvx9kcOl4o8w+JyT/8vxxyO+T65lYr8pXsUc8o7kNKwFx4VJIsBTsLllig8fwle9Sp4X8hZCvIKvf1yxc60UbEVJ9NFNQpoR5Z8nLteVkVAFjCdfIYaooG/XGJej295qfwtnJPlvDdweKx0D8ZrV248A87PTxTeiViQ0FjMBMoaiTU3mebxAmrZ0rcJa2f4XE5C0tJjeEtpMw4FoGnCRfkS3tPnZYfKfEdxj2xLBtN1g8RhDZ8/cSApF1cTYfmQ2YmXVEZbvh4jKrgCxyw6JWGe+SnXJotnj7Gs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
